- method: GET
  path: /login/:provider
  controller: OAuthController
  action: login

- method: GET
  path: /callback/:provider
  controller: OAuthController
  action: callback

- method: GET
  path: /version
  controller: VersionController
  action: show
